_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("art_poly_train_rotate_pos",)
  TEST: ("art_test",)


MODEL:
  WEIGHTS: ""  # or the provided pre-trained model
  TRANSFORMER:
    INFERENCE_TH_TEST: 0.4

SOLVER:
  IMS_PER_BATCH: 1
#  BASE_LR: 1e-5
#  LR_BACKBONE: 1e-6
  BASE_LR: 5e-6
  LR_BACKBONE: 5e-7
  WARMUP_ITERS: 0
  STEPS: (40000, 49000)
  MAX_ITER: 30000 #50000
  CHECKPOINT_PERIOD: 30000 #50000

INPUT:
  MIN_SIZE_TEST: 1440
  MAX_SIZE_TEST: 2560

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: ""
