_BASE_: "../Base.yaml"

DATASETS:
  TRAIN: ("totaltext_poly_train_rotate_pos",)
  TEST: ("totaltext_poly_test",) 

MODEL:
  WEIGHTS: ""

SOLVER:
  IMS_PER_BATCH: 1
#  BASE_LR: 1e-4
#  LR_BACKBONE: 1e-5
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (24000,)
  MAX_ITER: 20000
#  MAX_ITER: 30000
  CHECKPOINT_PERIOD: 100000 # No ckpt

TEST:
  EVAL_PERIOD: 500

OUTPUT_DIR: ""